# Generated by Django 2.1.2 on 2019-04-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='stripe_plan_id',
            new_name='plan_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='subscription_id',
        ),
        migrations.RenameField(
            model_name='usermembership',
            old_name='stripe_customer_id',
            new_name='customer_id',
        ),
    ]
